import Head from 'next/head'
import Card from '@/src/components/card/card'
import Button from '@/src/components/button/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Card description="You can now listen to millions of songs, audiobooks, and podcasts on any device anywhere you like!" />
      </div>
    </>
  )
}
